coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        flags:
          - backend
    patch:
      default:
        target: auto
        flags:
          - backend

flag_management:
  default_rules:
    carryforward: true

  individual_flags:
    - name: backend
      paths:
        - apps/backend/
      carryforward: true
